CREATE TABLE IF NOT EXISTS ai_message_feedback (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  message_id CHAR(36) NOT NULL UNIQUE,
  session_id CHAR(36) NOT NULL,
  user_id BIGINT NULL,
  provider VARCHAR(8) NOT NULL,
  provider_message_id VARCHAR(64) NOT NULL DEFAULT '',
  question VARCHAR(2000) NOT NULL,
  normalized_question VARCHAR(1000) NOT NULL DEFAULT '',
  answer TEXT NOT NULL,
  intent VARCHAR(48) NOT NULL DEFAULT '',
  confidence DECIMAL(5,4) NULL,
  intent_source VARCHAR(48) NOT NULL DEFAULT '',
  entities_json TEXT NOT NULL,
  tool_calls_json TEXT NOT NULL,
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  rating VARCHAR(8) NULL,
  reason VARCHAR(24) NULL,
  feedback_content VARCHAR(500) NOT NULL DEFAULT '',
  provider_sync_status VARCHAR(24) NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'OPEN',
  review_note VARCHAR(1000) NOT NULL DEFAULT '',
  reviewed_by BIGINT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  INDEX idx_ai_feedback_review (status, rating, updated_at),
  INDEX idx_ai_feedback_provider (provider, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
